# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='codigo_dependiente',
            field=models.IntegerField(null=True),
        ),
    ]
