# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 17:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0003_auto_20171110_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='saldoDeudor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='saldo_deudor'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='debe',
            field=models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='debe'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='haber',
            field=models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='haber'),
        ),
    ]
