# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0005_cuenta_saldoacreedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
