# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0007_auto_20171114_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='descripcion',
            field=models.CharField(default='null', max_length=256),
        ),
    ]
