# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 06:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0002_cuenta_codigo_dependiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletransaccion',
            name='debe',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='debe'),
        ),
        migrations.AlterField(
            model_name='detalletransaccion',
            name='haber',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='haber'),
        ),
    ]
